version: '3.8'

services:
  android-mcp:
    image: android-mcp:latest
    # Note: container_name is removed as it's deprecated
    # Note: build option moved to a separate docker-compose.build.yml file
    # Note: devices option moved to docker-compose.override.yml
    restart: always
    ports:
      - "3001:3001"    # MCP Server
      - "41641:41641"  # Tailscale
    volumes:
      - ./screenshots:/app/screenshots
      - tailscale-data:/var/lib/tailscale
    cap_add:
      - NET_ADMIN      # Required for Tailscale
      - NET_RAW        # Required for Tailscale
    environment:
      - TS_AUTHKEY=    # Set your Tailscale auth key here
      - DEFAULT_PHONE_IP=100.77.199.68 # Set your default Android device Tailscale IP
    # Note: devices option moved to docker-compose.override.yml

volumes:
  tailscale-data:
  # Removed unused n8n-data volume